data:
  path: 'https://raw.githubusercontent.com/amueller/scipy-2017-sklearn/091d371/notebooks/datasets/titanic3.csv'
  target_col: "survived"
  features:
    num:
      - "age"
      - "fare"
      - "pclass"
    cat:
      - "embarked"
      - "sex"

# TODO: Perform hyperparameter optimazation
#preprocessing:
#  params:

# TODO: Add support for multiple modells with Grid/Randomized Search
model:
  random_state: 42
  name: "logistic_regression"
  output_path: "models/titanic_pipeline.pkl"

# TODO: Perform hyperparameter optimazation
#  params:
#    C: [0.1, 1, 10]
#    penalty: ["l1", "l2"]
